Donut-Mod-Team/donut-mod

package-lock.json
package.json
prettier.config.js
tsconfig.json

- Add the basic configuration files needed for Node.js to run in compliance with TIBCO Spotfire's guidelines.
- The files are meant to be used as a starting point, in order to build upon and instantiate the project.
- Currently only some informative text is printed in the console and NodeJS just exits.

DMT-19 Introduce initial Node.js-related configuration files

---

.github/workflows/node.js.yml

- Set up the CI pipeline to install and run the node.js build to ensure tha the build succeeds on push and pull requests 
- Using github actions workflow to run our pipeline, tests to be added later

DMT-23 Create build related CI pipeline

---

LICENSE

- Helps DMT-18
- Addition of the MIT license to the project

Add license to the project

---

.gitignore
package-lock.json
package.json

Fixes DMT-31
Updates dependencies with security concerns. Removes unnecessary files from the repository, located in the dist folder. These have been added to the .gitignore.

DMT-31 Resolve dependencies and gitignore

---

src/donutState.js
src/renderer.js

- Closes DMT-42
- Add ratio value to tooltip
- Big refactor on percentage calculations, moved functions to only be used once and add percentage as a value to data

DMT-42 Refactor and add tooltip ratio

---

src/donutState.js
src/renderer.js
src/static/index.html
src/static/main.css
src/utility.js

- Helps DMT-36
- Add center text to the donut based on the sum of values
- Commented some recently added functions

DMT-36 Add center text 

---

src/renderer.js

- DMT-48
- Update logic for re-rendering of outer arc in order to fix issues with multiple error logs when re-rendering on data-update/change

DMT-48 Fix issue with rendering when changing data

---

src/renderer.js

Updated padding to correspond with the customers request. Padding between the sectors has now been reduced.
Closes DMT-46
- Reduced padding from 0.1 to 0.05
- This padding is more in line with what is present in the Pie Chart.

DMT-46 Update padding

---

src/renderer.js

- Closes DMT-51
- Fix the animation of the donut transition flickering

DMT-51 Fix animation flicker

---

src/donutState.js
src/renderer.js
src/static/index.html
src/static/main.css

- Closes #61, DMT-67
- Add default values for the center text 
- Fix bugs to be inline with current dev branch
- Does not scale well, to be implemented in the future

Add default center text values

---

src/donutState.js
src/renderer.js
src/static/main.css

- Closes #44 
- Make center text responsive by scaling with "..."
- Fix center sum

DMT-65 Add center text styling

---

src/popout.js

- Closes #81 
- Updated the naming of the labels to correspond with the desired naming conventions presented by the customer in #81.

DMT-83 Update labels naming

---

src/popout.js
src/static/main.css

- DMT-86
- Fix bug where settings icon is still visible in "viewing" mode

DMT-86 Fix settings icon visibility

---

src/utility.js
test/unit/utility.test.js

- DMT-87
- Add unit tests for the utility class

DMT-87 Unit tests

---

src/centerText.js
src/donutState.js
src/utility.js

- DMT-89
- Update logic for formating center value text 
- There may be some minor formating inconsistency with different browser languages

DMT-89 Fix formating center value

---

test/unit/utility.test.js

- DMT-87
- Add unit test for new method formatted sum in the utility class

DMT-87 Add unit test for formatted sum method

---

src/labels.js
src/main.js
src/popout.js
src/renderer.js
src/resources.js
src/utility.js

- Closes #80 
- Resize donut when labels rendered outside the donut
- Shorten label text when outside donut to fit mod container 
- Delete some old functionality to make this functionality work

DMT-85 Resize donut when labels outside

---

src/utility.js
test/unit/utility.test.js

- Helps DMT-87
- Added unit tests corresponding to the `checkIfRectangleGoOutside` method in `utilities.js` class.

Merge unit tests to dev

---

src/marker.js
src/renderer.js
src/resources.js

- Closes DMT-93
- Fix a marking issue for the left-side of the semi-circle.
- Updated the calculation of the start/end angle, in order to not having any negative representation of the angles in the code.

DMT-93 Merge bugfix for marking on semi-circle to dev

---

src/donutState.js
src/renderer.js

- Closes DMT-96
- Fix issue with hovering
- Fix issue with marking
- Fix issue with filtering
- Fix issue with sorting

DMT-96 Hotfix rendering bugs

---

src/donutState.js
src/labels.js
src/static/main.css

- DMT-97
- Fix issue with rendering labels null pointer
- Fix hovering id inconsistency issue with empty values and Math random causing id inconsistency

DMT-97 Update rendering labels

---

src/donutState.js

- Closes #110 Closes DMT-102
- Update label's values order to be consistent with the pie chart
- Fix issue where labels display value in parentheses that is not percentage

DMT-102 Update label's text

---

src/centerText.js
src/donutState.js
src/labels.js
src/main.js
src/renderer.js
src/resources.js
src/utility.js
test/unit/utility.test.js

- Helps DMT-106
- Update the center-text and labels value visualization, depending on the negative value representation chosen via Spotfire
- Minor refactoring
- Add comments to missing classes

Merge codebase-refactoring to dev

---

.github/workflows/codeql-config.yml
README.md

- Helps DMT-106 
- Add codeQL action to repository
- Add LGTM badges for warnings and code grade

Add code quality actions

---

README.md
documentation/user_guide.md

- Closes DMT-106
- Add donut chart gif in README
- Updated the user guide's hovering section

DMT-106 Merge documentation updates to main
